# Generated by Django 2.2.24 on 2021-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSubmission',
            fields=[
                ('TeamId', models.AutoField(primary_key=True, serialize=False)),
                ('VideoLink', models.CharField(max_length=500)),
                ('GithubLink', models.CharField(max_length=500)),
                ('ProjectIdea', models.CharField(max_length=1500)),
                ('CodingLanguages', models.CharField(max_length=1500)),
            ],
        ),
    ]
